$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_price_prediction_model
display_name: Train Car Price Prediction Model
description: Trains a Random Forest Regressor model
type: command
inputs:
  train_data:
    type: uri_folder
    description: Training data folder
  test_data:
    type: uri_folder
    description: Test data folder
  n_estimators:
    type: number
    description: Number of trees in the forest
    default: 100
  max_depth:
    type: number
    description: Maximum depth of trees
    default: 10
outputs:
  model_output:
    type: mlflow_model
    description: Trained MLflow model
code: ../../../src
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}
environment: azureml:machine_learning_E2E_v2@latest